# Toda imagen creada se basa en otra imagen
FROM node:22

# Se instala nodemon para el desarrollo
RUN npm i -g nodemon

# Crea el directorio de trabajo dentro del contenedor
RUN mkdir -p /home/app

# Se establece el directorio de trabajo dentro del contenedor
WORKDIR /home/app

# Se establece o expone el puerto que va a escuchar la aplicación
EXPOSE 3000

# Se establece el comando que se va a ejecutar al iniciar el contenedor para ejecutar la app
CMD ["nodemon", "index.js"]